<div class="info"></div>
<div style="width:750px;align:center;text-align:center;font-weight:bold;margin-top:5px;">
	<div>【快乐魔法】应用由上海乐鱼数码提供，若您在游戏中遇到问题，请<a href="http://page.renren.com/699136260" target="_blank">点击这里</a><br />联系方式：happyfish@hapyfish.com&nbsp;&nbsp;魔法客服QQ：800004811 &nbsp;&nbsp;工作时间：9:00-21:00</div>
    <div style="color:#3b5998;padding-top:2px;padding-bottom:12px;"><!-- <a href="javascript:addFavor();"><img src="{%$staticUrl%}/apps/island/images/common/favorite.png" style="top:6px;position:relative;padding-right:8px;" /></a> -->魔法教室号: {%$puid%} ({%$uid%})</div>
</div>

{%include file="cmscript.phtml"%}
</body>
</html>