<?php
class EventConditionType {
	CONST MIX_BUILDING = 1;
	CONST GIVE_ITEMS = 2;
	CONST TEACH_MAGIC_TIMES = 3;
	CONST REMOVE_MAGIC_EVENT = 4;
	CONST REMOVE_FRIENDS_EVENT = 5;
	CONST KILL_MONSTER = 6;
	CONST EXCHANGE_CRYSTAL = 7;
	CONST USE_MEDICINE = 8;
	CONST GAIN_CRYSTAL = 9;
	CONST VISIT_FRIENDS = 10;
	CONST USE_TRANS = 11;
	CONST USE_FRIENDS_TRANS = 12;
	CONST GIVE_BUILDINGS = 13;
	CONST DIY_HOUSE = 14;
	CONST PUT_CRYSTAL_FOR_CHANGE = 15;
}