<link rel="stylesheet" type="text/css" media="screen" href="{%$staticUrl%}/admin/css/ui-lightness/jquery-ui-1.8.16.custom.css" />
<link rel="stylesheet" type="text/css" media="screen" href="{%$staticUrl%}/admin/css/ui.jqgrid.css" />
<script src="{%$staticUrl%}/admin/js/jquery-1.5.2.min.js" type="text/javascript"></script>
<script src="{%$staticUrl%}/admin/js/i18n/grid.locale-cn.js" type="text/javascript"></script>
<script src="{%$staticUrl%}/admin/js/jquery.jqGrid.min.js" type="text/javascript"></script>

<style>
html, body {
    margin: 0;
    padding: 0;
    font-size: 12px;
}
.ui-jqgrid .ui-jqgrid-htable th div {
    height: 20px;
}
</style>

<div id="detail" style="">
	<div>
		<table><tr><td>导出工具↓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>快速导入工具↓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
			<tr>
				<td><form method="post" action="{%$baseUrl%}/hapyfishadmin/exportdata?table={%$tbName%}">
				  <input type="submit" id="btnExport" name="btnExport" value="备份导出" ></form></td>
				<td><form method="post" action="{%$baseUrl%}/hapyfishadmin/importdata?table={%$tbName%}" enctype="multipart/form-data">
				  <input type="file" name="filename"><input type="submit" name="btnImport" value="导入数据"></form></td>
			</tr>
			<tr><td></td><td></td></tr>
			{% if $candel %}
			<tr><td>删除工具-></td><td><form method="post" action="{%$baseUrl%}/hapyfishadmin/deldata?table={%$tbName%}&key={%$candel%}">
				  <select name="selVal">{% foreach from=$selDelList key=key item=data %}<option value="{%$key%}">{%$data%}</option>{% /foreach %}</select>
				  <input type="submit" id="btnDel" value="删除数据" /><span style="color:red">***小心使用！建议先备份导出下***</span></form></td></tr>
			{% /if %}
		</table>
	</div>
	<!-- <div id="jqTable"></div> -->
	<table id="jqTable"></table>
	<div id="pager"></div>
</div><!--/#detail-->

<script type="text/javascript">
    $(document).ready(function() {
    	initjqGrid();
    });


    function initjqGrid() {
    	$("#jqTable").jqGrid({
    		datatype: "local",
    		data: {%$lstData%},
    		height: '550',
    	   	colNames: $.parseJSON('{%$colNames%}'),//['操作', 'Inv No','Date', 'Client', 'Amount','Tax','Total','Notes'],
    	   	colModel: $.parseJSON('{%$colModel%}'),
    	   	multiselect: true,
    	   	rowNum: 20,
    	   	rowList: [20,50],
    	   	pager: '#pager',
    	    viewrecords: true,
    	    autowidth: true,

    	   	gridComplete: function(){
    			var ids = $("#jqTable").jqGrid('getDataIDs');
    			for(var i=0;i < ids.length;i++){
    				var cl = ids[i];
    				be = "<input style='height:25px;width:30px;' type='button' value='E' onclick=\"$('#jqTable').editRow('"+cl+"');\"  />";
    				se = "<input style='height:25px;width:30px;' type='button' value='S' onclick=\"$('#jqTable').saveRow('"+cl+"',false,null,null,savedone);\"  />";
    				ce = "<input style='height:25px;width:30px;' type='button' value='C' onclick=\"$('#jqTable').restoreRow('"+cl+"', cancel);\" />";
    				$("#jqTable").jqGrid('setRowData',ids[i],{actopt:be+se+ce});
    			}
    		},

    		loadComplete: function(resp) {
        		//alert('aa');
        		//alert(resp);
    		},
    		editurl: "savedata?table={%$tbName%}",
    		caption: "{%$tbShowName%}"+"({%$tbName%})"

    	});

    	/*var mydata = $.parseJSON('{%$lstData%}');
    	for(var i=0;i<=mydata.length;i++) {
    		$("#jqTable").jqGrid('addRowData',i+1,mydata[i]);
    	}*/

    	$("#jqTable").jqGrid('navGrid',"#pager",{edit:false,add:false,del:false});
    	/*.navButtonAdd('#pager',{
 		   caption:"Add",
		   buttonicon:"ui-icon-add",
		   onClickButton: function(){
		     alert("Adding Row");
		   },
		   position:"last"
		});*/


    }

    function savedone(rid, resp) {
		if (resp.responseText == 'complete') {
			alert('更新成功');
			if (rid.indexOf('_') == -1) {
			}
			else {
				parent.showDetail('{%$tbName%}');
			}
			return;
		}
    }

    function cancel(rid) {
    	if (rid.indexOf('_') == -1) {
		}
		else {
			parent.showDetail('{%$tbName%}');
		}
		return;
    }

    function doExport() {
    	var tbName = $("#table").val();
    	$.ajax({
            type: 'POST',
            url: '/hapyfishadmin/exportdata',
            data: {'table': tbName},
            dataType: 'text',
            timeout: 30000,
            success: function(resp){
            	if (resp.status==1) {
                	alert(resp.msg);
            		$('#errMsg').html('*****处理完成!*****'+resp.tm).fadeOut(3000);
            	}
            	else {
            		$('#errMsg').html('*****失败，请稍后再试*****' + resp.msg);
                }
            },
    		error: function(resp){
    			ffdebug('err:'+resp);
    		},
    		complete: function(resp){
    			//ffdebug('complete:'+resp);
    			$('#btnSubmit').attr('disabled', false);
    		}
 		});
    }
</script>
