<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Cache-Control" content="no-cache" />
	<meta http-equiv="imagetoolbar" content="no" />
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<!--[if lt IE 7]><![endif]-->
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js?v=1.00" type="text/javascript"></script>
	<link rel="stylesheet" href="{%$staticUrl%}/css/admin.css?v=1.00" type="text/css" media="all" />
	<title>快乐魔法后台管理</title>
</head>

<body id="admin">