<link href="{%$staticUrl%}/apps/island/css.css?v=2.6" rel="stylesheet" type="text/css" />
<style type="text/css">
    #notice li a:hover,a:link,a:visited {
        color:red;
    }
</style>
<div class="main">
    <div class="title">
        <div class="menu">
            <div class="logo">
                <img src="{%$staticUrl%}/apps/island/images/sl_03.gif" alt="快乐岛主" />
            </div>
            <ul>
                <li><a href="#" onclick="XNML.appFan();"><img src="{%$staticUrl%}/apps/island/images/sl_17.gif" alt="成为粉丝" /></a></li>
                <li><a href="http://apps.{%$domain%}/rrisland/pay/top"><img src="{%$staticUrl%}/apps/island/images/sl_15.gif" alt="充值" /></a></li>
                <li><a href="http://group.renren.com/GetThread.do?id=330727427&parentpage=&curpage=0&label=&tribeId=320022384" target="_blank"><img src="{%$staticUrl%}/apps/island/images/sl_13.gif" alt="帮助" /></a></li>
                <li><a href="http://group.renren.com/GetTribe.do?id=320022384" target="_blank"><img src="{%$staticUrl%}/apps/island/images/sl_11.gif" alt="讨论" /></a></li>
                <li><a href="http://apps.{%$domain%}/rrisland/gift/top"><img src="{%$staticUrl%}/apps/island/images/sl_09.gif" alt="赠送礼物" /></a></li>
                <li><a href="http://apps.{%$domain%}/rrisland/invite/top"><img src="{%$staticUrl%}/apps/island/images/sl_07.gif" alt="邀请好友" /></a></li>
                <li><a href="http://apps.{%$domain%}/rrisland/beta"><img src="{%$staticUrl%}/apps/island/images/sl_05.gif" alt="游戏首页" /></a></li>
            </ul>
        </div>
    </div>

    <div id="swfcontent">
        <xn:iframe addxnsig="true" frameborder="0" src="http://rrisland.hapyfish.com/beta/flash" width="748" height="650" />
    </div>
</div>