<link href="{%$staticUrl%}/css/style.css" rel="stylesheet" type="text/css" />
<div class="magic">
    <div class="pay">
        <table border="0" cellspacing="0" cellpadding="0" id="pay_table" class="pay_table">
            <tr>
                <td colspan="3" class="pay_table_head"></td>
            </tr>
            <tr>
                <td class="pay_table_left"></td>
                <td class="pay_table_center">
                    <div class="pay_info">
                        <table border="0" cellspacing="0" cellpadding="0" id="pay_table_info" class="pay_table_info">
                            <tr>
                                <td rowspan="2" style="width: 60px; height: 60px; background: #fff;"><img src="{%$user.face%}" width="60" height="60" /></td>
                                <td style="text-align: left; text-indent: 6px; color: #3B8DAF;" valign="bottom">{%$user.name|escape%}</td>
                            </tr>
                            <tr>
                                <td id="pay_info_ico">钻石：{%$user.gold%}</td>
                            </tr>
                        </table>
                    </div>
                    <div class="pay_log">
                        <table border="0" cellspacing="0" cellpadding="0" id="pay_table_log" class="pay_table_log">
                            <tr>
                                <td valign="bottom">
                                    <table border="0" cellspacing="0" cellpadding="0" id="pay_menu" class="pay_menu">
                                        <tr>
                                            <td valign="bottom" class="pay_menu_normal" id="pay_menu_0" onclick="">充值钻石</td>
                                            <td style="width: 5px;"></td>
                                            <td valign="bottom" class="pay_menu_default" id="pay_menu_1" onclick="">充值记录</td>
                                            <td style="width: 5px;"></td>
                                            <td valign="bottom" class="pay_menu_normal" id="pay_menu_2" onclick="">消费记录</td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td valign="top">
                                    <div id="pay_list_1" class="pay_list" style="">
                                        <table border="0" cellspacing="0" cellpadding="0" id="pay_list_table1" class="pay_list_table">
                                            <tr>
                                                <td colspan="4" style="text-align: left; text-indent: 24px; height: 28px; line-height: 28px;">充值记录 <span style="color: #7D8D8D;">共57条</span></td>
                                            </tr>
                                            <tr class="pay_list_table_tr1">
                                                <td style="width: 180px; height: 38px;">日期</td>
                                                <td style="width: 80px; height: 38px;">充值宝石数量</td>
                                                <td style="width: 250px; height: 38px;">消费</td>
                                                <td style="height: 38px;">充值方式</td>
                                            </tr>
                                            <tr>
                                                <td>2011-04-16 20:39:14</td>
                                                <td style="color: #F00;">1</td>
                                                <td>0人人豆</td>
                                                <td>系统赠送</td>
                                            </tr>
                                            <tr>
                                                <td>2011-04-16 20:39:14</td>
                                                <td style="color: #F00;">1</td>
                                                <td>0人人豆</td>
                                                <td>系统赠送</td>
                                            </tr>
                                            <tr>
                                                <td>2011-04-16 20:39:14</td>
                                                <td style="color: #F00;">1</td>
                                                <td>0人人豆</td>
                                                <td>系统赠送</td>
                                            </tr>
                                            <tr>
                                                <td>2011-04-16 20:39:14</td>
                                                <td style="color: #F00;">1</td>
                                                <td>0人人豆</td>
                                                <td>系统赠送</td>
                                            </tr>
                                            <tr>
                                                <td>2011-04-16 20:39:14</td>
                                                <td style="color: #F00;">1</td>
                                                <td>0人人豆</td>
                                                <td>系统赠送</td>
                                            </tr>
                                            <tr>
                                                <td>2011-04-16 20:39:14</td>
                                                <td style="color: #F00;">1</td>
                                                <td>0人人豆</td>
                                                <td>系统赠送</td>
                                            </tr>
                                            <tr>
                                                <td colspan="4">
                                                    <div class="global_page">
                                                        <ul>
                                                            <li class="global_page_normal"><a href="#">[01]</a></li><li><a href="#">[02]</a></li><li><a href="#">[03]</a></li><li><a href="#">[04]</a></li>
                                                        </ul>
                                                    </div>
                                                </td>
                                            </tr>
                                        </table>

                                    </div>
                                    <div id="pay_list_2" class="pay_list" style="display: none;">
                                        <table border="0" cellspacing="0" cellpadding="0" id="pay_list_table2" class="pay_list_table">
                                            <tr>
                                                <td colspan="4" style="text-align: left; text-indent: 24px; height: 28px; line-height: 28px;">消费记录 <span style="color: #7D8D8D;">共57条</span></td>
                                            </tr>
                                            <tr class="pay_list_table_tr1">
                                                <td style="width: 180px; height: 38px;">日期</td>
                                                <td style="width: 80px; height: 38px;">充值宝石数量</td>
                                                <td style="width: 250px; height: 38px;">消费</td>
                                                <td style="height: 38px;">充值方式</td>
                                            </tr>
                                            <tr>
                                                <td>2011-04-16 20:39:14</td>
                                                <td style="color: #F00;">1</td>
                                                <td>0人人豆</td>
                                                <td>系统赠送</td>
                                            </tr>
                                            <tr>
                                                <td>2011-04-16 20:39:14</td>
                                                <td style="color: #F00;">1</td>
                                                <td>0人人豆</td>
                                                <td>系统赠送</td>
                                            </tr>
                                            <tr>
                                                <td>2011-04-16 20:39:14</td>
                                                <td style="color: #F00;">1</td>
                                                <td>0人人豆</td>
                                                <td>系统赠送</td>
                                            </tr>
                                            <tr>
                                                <td>2011-04-16 20:39:14</td>
                                                <td style="color: #F00;">1</td>
                                                <td>0人人豆</td>
                                                <td>系统赠送</td>
                                            </tr>
                                            <tr>
                                                <td>2011-04-16 20:39:14</td>
                                                <td style="color: #F00;">1</td>
                                                <td>0人人豆</td>
                                                <td>系统赠送</td>
                                            </tr>
                                            <tr>
                                                <td>2011-04-16 20:39:14</td>
                                                <td style="color: #F00;">1</td>
                                                <td>0人人豆</td>
                                                <td>系统赠送</td>
                                            </tr>
                                            <tr>
                                                <td colspan="4">
                                                    <div class="global_page">
                                                        <ul>
                                                            <li class="global_page_normal"><a href="#">[01]</a></li><li><a href="#">[02]</a></li><li><a href="#">[03]</a></li><li><a href="#">[04]</a></li>
                                                        </ul>
                                                    </div>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
                <td class="pay_table_right"></td>
            </tr>
            <tr>
                <td colspan="3" class="pay_table_foot"></td>
            </tr>
        </table>
    </div>
</div>
