<link href="{%$staticUrl%}/css/style.css" rel="stylesheet" type="text/css" />
<div class="magic">
    <div class="pay">
        <table border="0" cellspacing="0" cellpadding="0" id="pay_table" class="pay_table">
            <tr>
                <td colspan="3" class="pay_table_head"></td>
            </tr>
            <tr>
                <td class="pay_table_left"></td>
                <td class="pay_table_center">
                    <div class="pay_info">
                        <table border="0" cellspacing="0" cellpadding="0" id="pay_table_info" class="pay_table_info">
                            <tr>
                                <td rowspan="2" style="width: 60px; height: 60px; background: #fff;"><img src="{%$user.face%}" width="60" height="60" /></td>
                                <td style="text-align: left; text-indent: 6px; color: #3B8DAF;" valign="bottom">{%$user.name|escape%}</td>
                            </tr>
                            <tr>
                                <td id="pay_info_ico">钻石：{%$user.gold%}</td>
                            </tr>
                        </table>
                    </div>
                    <div class="pay_log" style="height:480px">
                        {%$msg%}<br/>
						<a href="#" onclick="orderlist();">返回</a>
                    </div>
                </td>
                <td class="pay_table_right"></td>
            </tr>
            <tr>
                <td colspan="3" class="pay_table_foot"></td>
            </tr>
        </table>
    </div>
</div>
<script type="text/javascript">
    function orderlist()
    {
    	HFApp.loadHtml('/pay/orderlist', 'POST', {}, 'text', 'payIframe');
    }
</script>
