<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>帮助 | 快乐岛主</title>
<link href="{%$staticUrl%}/apps/island/css_2011041102.css?v=1.01" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--

-->
.table-txt{ align:center; line-height:15px;}
.STYLE3 {
	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
.STYLE1 {
	color: #1363b7;
	font-size: 14px;
	align:left;
	font-style: normal;
	line-height: 30px;
	font-weight: bold;
}
</style>
</head>

<body>
<div class="main">

{%include file="menu.phtml"%}

<div class="content" style="height:860px;">
  <div style="height:185px; background-image:url({%$staticUrl%}/apps/island/images/help/h-title.gif); background-repeat:no-repeat;">
    <table width="748" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td height="177" align="center" valign="bottom"><table width="740" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><div  class="STYLE3">
              <div align="right"><a href="{%$baseUrl%}/help/top">[基本介绍]&nbsp;</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help2">&nbsp;[操作说明]&nbsp;</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help5">&nbsp;[资费说明和支付方式]</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help6">&nbsp;[常见问答]</a></div>
            </div></td>
          </tr>
          <tr>
            <td><hr size="1" /></td>
          </tr>
          <tr>
            <td><div class="STYLE3">
              <div align="right"><a href="{%$baseUrl%}/help/help6">1.基本信息和操作</a>&nbsp;&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help9">2.互动操作</a></div>
            </div></td>
          </tr>
        </table></td>
      </tr>
    </table>
  </div>
  <div style="height:660px;" >
    <table width="710" border="0" align="center" cellpadding="0" cellspacing="0" class='STYLE3'>
      <tr>
        <td height="40"><p align="left" class="STYLE9"><img src="{%$staticUrl%}/apps/island/images/help/h10.gif" alt="基本操作" width="208" height="21" /></p></td>
      </tr>
      <tr>
        <td height="22"><strong>2) 互动操作</strong></td>
      </tr>
      <tr>
        <td><table width="710" border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td><strong>Q：如何去好友岛屿 </strong></td>
            </tr>
            <tr>
              <td>A：在游戏主界面下方，是您的好友界面，在游戏中的好友都会显示他们的头像。只要直接点击他们的头像，就能访问他们的岛屿啦！</td>
            </tr>
          </table>
            <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：如何从好友岛屿回到自己岛屿？</strong></td>
              </tr>
              <tr>
                <td>A：在好友岛屿上，游戏有下面有一个“go home”回家按钮，直接点击就可以回到自己的岛屿。或者在好友头像中找到自己的头像，点击也能回到自己的岛屿。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：在好友岛屿上能做什么？</strong></td>
              </tr>
              <tr>
                <td>A：在好友岛屿上，我们可以拾取金币，拉好友游客，帮助好友处理故障。当看到好友设施上有金币出现时，我们可以直接点击拾取金币；当看到好友游船靠岸时，我们可以点击游船拉走好友游客；当看到好友设施冒烟时，我们可以点击设施修理故障获得经验。我们所有的行为都会记录在好友的日志中。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q:为什么不能偷拉好友的客人 </strong></td>
              </tr>
              <tr>
                <td>如果好友的客人被其它人偷走过，船只会显示灰色，就不能再偷啦！再点击就会提示“这船上的客人太少了，就给TA留点吧”！ </td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q:如何给其他玩家发好友消息 </strong></td>
              </tr>
              <tr>
                <td>A：进入好友岛屿后，点击左下角“铃铛”提醒。在弹出消息窗口，即可提醒好友收船、收钱以及自定义发送消息给好友。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q:如何在快乐岛主中回复好友消息 </strong></td>
              </tr>
              <tr>
                <td>A：在自己小岛，点击左下角“铃铛”提醒。在弹出窗口，即可查看好友在“快乐岛主”中给您发的消息了。可直接在以下输入框里输入内容，点击“回复”，就可以了。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：我收到的礼物在哪里？</strong></td>
              </tr>
              <tr>
                <td>A：在日志或社区页面看到收到礼物的信息，当您进入游戏，您可以在装扮岛屿界面中的仓库中看到您收到的礼物道具。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：如何送礼？</strong> </td>
              </tr>
              <tr>
                <td>A：在游戏最上部有一个“赠送礼物”的按钮，点击就会进入赠送礼物页面，选择您想送的礼物，然后点击您想送的好友，确认就发出礼物了。礼物是不花任何金币的。</td>
              </tr>
            </table></td>
      </tr>
    </table>
  </div>
  

</div>

</body>
</html>
