<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>帮助 | 快乐岛主</title>
<link href="{%$staticUrl%}/apps/island/css_2011041102.css?v=1.01" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
.STYLE1 {
	color: #1363b7;
	font-size: 14px;
	align:left;
	font-style: normal;
	line-height: 30px;
	font-weight: bold;
}
.STYLE2 {
	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}

-->
.table-txt{ align:center; line-height:15px;}
.STYLE3 {
	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 18px;
	color: #333333;
	text-align: left;
}
.STYLE87 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
</style>
</head>

<body>
<div class="main">

{%include file="menu.phtml"%}

<div class="content" style="height:860px;padding-top:2px;">
  <div style="height:185px; background-image:url({%$staticUrl%}/apps/island/images/help/h-title.gif); background-repeat:no-repeat;">
    <table width="748" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td height="177" align="center" valign="bottom"><table width="740" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><div  class="STYLE87">
                <div align="right"><a href="{%$baseUrl%}/help/top">[基本介绍]&nbsp;</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help2">&nbsp;[操作说明]&nbsp;</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help5">&nbsp;[资费说明和支付方式]</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help6">&nbsp;[常见问答]</a></div>
            </div></td>
          </tr>
          <tr>
            <td><hr size="1" /></td>
          </tr>
          <tr>
            <td><div >
                <div align="right"><a href="{%$baseUrl%}/help/help6">1.基本信息和操作&nbsp;</a>&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help9">2.互动操作</a></div>
            </div></td>
          </tr>
        </table></td>
      </tr>
    </table>
  </div>
  <div style="height:660px;">
    <table width="710" border="0" align="center" cellpadding="0" cellspacing="0" class="STYLE3">
      <tr>
        <td height="40"><p align="left"><img src="{%$staticUrl%}/apps/island/images/help/h10.gif" alt="基本操作" width="208" height="21" /></p></td>
      </tr>
      <tr>
        <td height="22"><strong>1)基本信息和操作</strong></td>
      </tr>
      <tr>
        <td><table width="710" border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td><strong>Q：为什么我的小岛出现禁止标示？</strong></td>
            </tr>
            <tr>
              <td>A：这是因为您的小岛建筑设施摆放的位置不对，岛上的建筑要求必须有一个出路，如果四面的路都被堵死，就会出现禁止标志。不过，出现了这个标志也没关系，您只需要点击“海岛装饰”重新摆放设施，留出空路即可。 </td>
            </tr>
          </table>
            <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：遇到“未营业”的设施怎么办？</strong></td>
              </tr>
              <tr>
                <td>A：“未营业”的设施意味着还没有游客选择消费，这个时候我们可以通过释放新的游客上岛或去好友岛屿拉游客来增加游客进入设施的几率。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：装饰度是什么？</strong></td>
              </tr>
              <tr>
                <td>A：装饰度代表岛屿上的装饰程度，每安置一个1星设施和装饰道具我们都会+1装饰度，安置2星设施就会+2装饰度，以此类推。装饰度的作用有2点：1是增加游船带来游客的数量，2是一些设施需要装饰度达到一定数值才能购买‘</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：装饰度不够是什么原因？</strong></td>
              </tr>
              <tr>
                <td>A：就是您放在小岛上的设施没有达到一定的数量，就会提示装饰度不够，可以去“海岛装饰”购买哦！</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：如何修理故障？</strong></td>
              </tr>
              <tr>
                <td>A：当我们看到岛屿上有设施冒烟，就说明这个设施出了故障，这个时候我们可以通过点击烟雾来修理设施，会增加我们的经验。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：如何升级设施？</strong></td>
              </tr>
              <tr>
                <td>A：点击设施，弹出升级面板，当条件满足时就能升级，升级设施跟您的等级、装饰度、金币或宝石相关的。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：如何升级船只？</strong></td>
              </tr>
              <tr>
                <td>A：在航行状态中点击船只，出现升级面板，条件满足就能升级，升级船只后请您返回您升级的船位，把解锁的船只勾选一下，就可以替换了。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：如何扩展船位？</strong></td>
              </tr>
              <tr>
                <td>A：点击扩展标志，出现扩展面板，条件满足就能升级&nbsp;，扩展船位跟您的好友人数息息相关的噢。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="650" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>
                <td height="20"><div align="right"><a href="{%$baseUrl%}/help/help6">上一页</a>&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help8">下一页</a></div></td>
              </tr>
            </table></td>
      </tr>
    </table>
  </div>
  

</div>

</body>
</html>
