<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>帮助 | 快乐岛主</title>
<link href="{%$staticUrl%}/apps/island/css_2011041102.css?v=1.01" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
.STYLE1 {
	color: #1363b7;
	font-size: 14px;
	align:left;
	font-style: normal;
	line-height: 30px;
	font-weight: bold;
}
.STYLE2 {
	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}

-->
.table-txt{ align:center; line-height:15px;}
.STYLE3 {
	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 18px;
	color: #333333;
	text-align: left;
}
.STYLE87 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
</style>
</head>

<body>
<div class="main">

{%include file="menu.phtml"%}

<div class="content" style="height:860px;padding-top:2px;">
  <div style="height:185px; background-image:url({%$staticUrl%}/apps/island/images/help/h-title.gif); background-repeat:no-repeat;">
    <table width="748" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td height="177" align="center" valign="bottom"><table width="740" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><div>
                <div align="right"><a href="{%$baseUrl%}/help/top">[基本介绍]&nbsp;</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help2">&nbsp;[操作说明]&nbsp;</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help5">&nbsp;[资费说明和支付方式]</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help6">&nbsp;[常见问答]</a></div>
            </div></td>
          </tr>
          <tr>
            <td><hr size="1" /></td>
          </tr>
          <tr>
            <td><div>
                <div align="right"><a href="{%$baseUrl%}/help/help6">1.基本信息和操作</a>&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help9">&nbsp;2.互动操作</a></div>
            </div></td>
          </tr>
        </table></td>
      </tr>
    </table>
  </div>
  <div style="height:660px;">
    <table width="710" border="0" align="center" cellpadding="0" cellspacing="0" class="STYLE3">
      <tr>
        <td height="40"><p align="left" class="STYLE9"><img src="{%$staticUrl%}/apps/island/images/help/h10.gif" alt="基本操作" width="208" height="21" /></p></td>
      </tr>
      <tr>
        <td height="22" class="STYLE1">1) <strong>基本信息和操作</strong></td>
      </tr>
      <tr>
        <td><table width="710" border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td><strong>Q：如何玩游戏，怎么获得金币？</strong></td>
            </tr>
            <tr>
              <td>A：在岛上购买并安置设施（房子），点击靠岸的游船（如果没游船靠岸需要等待），就会有游客自动上岛消费，等设施结算时间到，就可以收金币了（房子和设施上面会有金币）。</td>
            </tr>
          </table>
            <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：怎么购买和使用设施?</strong></td>
              </tr>
              <tr>
                <td>A：1、点击游戏左下角类似刷子形状的按钮，就能进入装扮岛屿界面，在这里，您可以购买、安放、出售各类设施和装饰性道具。<br />
                  2、只要点击选择您想要的道具，然后移动鼠标到自己岛屿上可以安放的位置，再点击一次就完成安放。<br />
                  3、最后点击右下部绿色打钩按钮就可以确认了哦。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：小岛仓库在哪？</strong></td>
              </tr>
              <tr>
                <td>A：1、进入快乐岛主游戏页面，点击页面下方第一个按钮“海岛装饰”<br />
                  2、再点最后一个按钮“仓库”就能看到仓库里的物品了，好友赠送的礼物也放在这里的哦！</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：如何退出装扮岛屿的界面？</strong></td>
              </tr>
              <tr>
                <td>A：在装扮岛屿界面，您可以点击右下部的蓝色返回按钮来取消您的购买和安置动作，也可以点击绿色打钩按钮来确认购买和安置动作。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：如何获得经验升级？</strong></td>
              </tr>
              <tr>
                <td>A：以下动作都会产生经验：点击游船，收取金币，游客进入设施，修理设施故障，升级船只，扩展船位，完成任务。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：升级有什么好处？</strong> </td>
              </tr>
              <tr>
                <td>A：升级可能会赠送道具卡、岛屿面积放大、游客数量上限增加、解锁高级设施、解锁高级游船</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：游船有什么用？</strong></td>
              </tr>
              <tr>
                <td>A：游船是目前游戏中带来游客的必须工具，游客必须有游船才会到岛上来。当游船在航行中时，我们只能等待或使用加速卡或升级游船。当游船靠岸后，我们可以点击游船释放游客上岛。当岛屿游客上限满了后，游船如果还有多余游客也会在港口等待知道下一次点击。如果我们不点击游船，好友就可以来我们岛上拉走我们的游客。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：设施上的灯泡是什么？</strong></td>
              </tr>
              <tr>
                <td>A：设施有灯泡亮起代表设施内有游客，在营业中。等设施结算时间到，您就可以收取金币了。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="650" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>
                <td height="20"><div align="right"><a href="{%$baseUrl%}/help/help7">下一页</a></div></td>
              </tr>
            </table>
        
    </table>
  </div>
  

</div>

</body>
</html>
