<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>帮助 | 快乐岛主</title>
<link href="{%$staticUrl%}/apps/island/css_2011041102.css?v=1.01" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
.STYLE1 {
	color: #1363b7;
	font-size: 14px;
	align:left;
	font-style: normal;
	line-height: 30px;
	font-weight: bold;
}
.STYLE2 {
	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}

-->
.table-txt{ align:center; line-height:15px;}
.STYLE3 {
	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 18px;
	color: #333333;
	text-align: left;
}
.STYLE87 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
</style>
</head>

<body>
<div class="main">

{%include file="menu.phtml"%}

<div class="content" style="height:860px;padding-top:2px;">
  <div style="height:185px; background-image:url({%$staticUrl%}/apps/island/images/help/h-title.gif); background-repeat:no-repeat;">
    <table width="748" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td height="177" align="center" valign="bottom"><table width="740" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><div>
                <div align="right"><a href="{%$baseUrl%}/help/top">[基本介绍]&nbsp;</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help2">&nbsp;[操作说明]&nbsp;</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help5">&nbsp;[资费说明和支付方式]</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help6">&nbsp;[常见问答]</a></div>
            </div></td>
          </tr>
          <tr>
            <td><hr size="1" /></td>
          </tr>
          <tr>
            <td><div >
                <div align="right"><a href="{%$baseUrl%}/help/help2">1.基本操作&nbsp;</a>&nbsp;<a href="{%$baseUrl%}/help/help3">2.游戏攻略</a></div>
            </div></td>
          </tr>
        </table></td>
      </tr>
    </table>
  </div>
  <div style="height:660px;">
    <table width="710" border="0" align="center" cellpadding="0" cellspacing="0" class="STYLE89">
      <tr>
        <td height="40"><p align="left" class="STYLE9"><img src="{%$staticUrl%}/apps/island/images/help/h08.gif" alt="基本介绍" /></p></td>
      </tr>
      <tr>
        <td height="22"><div align="left" class="STYLE88"><strong>2)游戏攻略</strong></div></td>
      </tr>
      <tr>
        <td><table width="710" border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td><p class="STYLE32"><strong>【好友】 </strong></p></td>
            </tr>
            <tr>
              <td>好友分为两种类型，一种为保守型、一种为开放型。简单的说保守就是各自发展保守关岛型，无法被偷金钱。开放型不言而喻就是开放，可以随意玩。大家选择时要谨慎选择，如你是开放型玩家则加了很多保守型的玩家，那你的命运…………</td>
            </tr>
            <tr>
              <td><table width="650" border="0" align="center" cellpadding="0" cellspacing="0">
                  <tr>
                    <td height="20"><hr size="1" /></td>
                  </tr>
              </table></td>
            </tr>
          </table>
            <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>【其他】</strong></td>
              </tr>
              <tr>
                <td><p class="STYLE35">船多人多可以刷经验-简单的说一次全船的人都下了你+3点经验。一次就下1个人也+3点经验。这就看你的操作咯。提示一下-岛满人就不会进人，刚好出人则可进人。保持的饱满的人数极少的出岛人数，则可赚取船上顾客进到所给的3点经验。 <br />
                  进岛的顾客如不满意走的不算，留下的会在消费完毕后为表示满意变个大桃心出来，每个人给1点经验。 </p></td>
              </tr>
              <tr>
                <td><table width="650" border="0" align="center" cellpadding="0" cellspacing="0">
                    <tr>
                      <td height="20"><hr size="1" /></td>
                    </tr>
                </table></td>
              </tr>
            </table>
          <table width="650" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>
                <td height="20"><div align="right"><a href="{%$baseUrl%}/help/help3">上一页</a></div></td>
              </tr>
            </table>
          <p class="STYLE10">&nbsp;</p></td>
      </tr>
    </table>
  </div>
  

</div>

</body>
</html>
