<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>帮助 | 快乐岛主</title>
<link href="{%$staticUrl%}/apps/island/css_2011041102.css?v=1.01" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
.STYLE1 {
	color: #1363b7;
	font-size: 14px;
	align:left;
	font-style: normal;
	line-height: 30px;
	font-weight: bold;
}
.STYLE2 {
	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}

-->
.table-txt{ align:center; line-height:15px;}
.STYLE3 {
	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 18px;
	color: #333333;
	text-align: left;
}
.STYLE19 {	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 18px;
	color: #333333;
	text-align: left;
}
.STYLE20 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 18px;
	color: #333333;
	text-align: left;
}
.STYLE21 {	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 18px;
	color: #333333;
	text-align: left;
}
.STYLE87 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
</style>
</head>

<body>
<div class="main">

{%include file="menu.phtml"%}

<div class="content" style="height:860px;padding-top:2px;">
  <div style="height:185px; background-image:url({%$staticUrl%}/apps/island/images/help/h-title.gif); background-repeat:no-repeat;">
    <table width="748" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td height="177" align="center" valign="bottom"><table width="740" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><div>
                <div align="right"><a href="{%$baseUrl%}/help/top">[基本介绍]&nbsp;</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help2">&nbsp;[操作说明]&nbsp;</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help5">&nbsp;[资费说明和支付方式]</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help6">&nbsp;[常见问答]</a></div>
            </div></td>
          </tr>
          <tr>
            <td><hr size="1" /></td>
          </tr>
          <tr>
            <td><div>
                <div align="right"><a href="{%$baseUrl%}/help/help2">1.基本操作&nbsp;</a>&nbsp;<a href="{%$baseUrl%}/help/help3">2.游戏攻略</a></div>
            </div></td>
          </tr>
        </table></td>
      </tr>
    </table>
  </div>
  <div style="height:660px;">
    <table width="710" border="0" align="center" cellpadding="0" cellspacing="0">
      <tr>
        <td height="40"><p align="left" class="STYLE9"><img src="{%$staticUrl%}/apps/island/images/help/h08.gif" alt="基本介绍" /></p></td>
      </tr>
      <tr>
        <td height="22"><div align="left" class="STYLE89"><strong>1) 基本操作</strong></div></td>
      </tr>
      <tr>
        <td valign="top"><table width="710" border="0" cellpadding="0" cellspacing="0" class="STYLE3">
            <tr>
              <td width="345">【设施建设】</td>
              <td width="10">&nbsp;</td>
              <td width="355">【任务】</td>
            </tr>
            <tr>
              <td><p>用户可通过DIY来装扮自己的小岛，通过不断的升级，岛屿会变的越来越大，可以建设的设施也会越来越多。 <br />
                建筑的建设分为初级普通建筑和后期高级建筑和宝石建筑。</p></td>
              <td>&nbsp;</td>
              <td valign="top"><p>游戏中提供玩家丰富的任务，引导帮助玩家建设自己的小岛，完成任务可以获得高额的经验和金钱哦，任务分日常、建设和成就三个系列，除了获得金钱经验外，还能获得称号，你是大财主还是破坏专家，游戏中由你决定。&nbsp; </p></td>
            </tr>
            <tr>
              <td><div align="center"><img src="{%$staticUrl%}/apps/island/images/help/h01.gif" width="240" height="170"  /></div></td>
              <td>&nbsp;</td>
              <td><div align="center"><img src="{%$staticUrl%}/apps/island/images/help/h02.gif" width="240" height="170"/></div></td>
            </tr>
          </table>
            <table width="710" border="0" cellpadding="0" cellspacing="0" class="STYLE88">
              <tr>
                <td width="345">【港湾船位】</td>
                <td width="10">&nbsp;</td>
                <td width="355">【道具卡使用】</td>
              </tr>
              <tr>
                <td><p>小岛需要有游客才能赚钱，游客都是乘坐各类的船只前来，不断的扩展自己船坞的船位，升级高级的船只，能有效的增加前来岛屿的游客数量，增加岛屿收入数。 </p></td>
                <td>&nbsp;</td>
                <td valign="top"><p>游戏中可以利用道具卡给自己的船只加速，设施加时，并且可以利用破坏型的道具到好友的岛上去捣乱，增加游戏的乐趣。 </p></td>
              </tr>
              <tr>
                <td><div align="center"><img src="{%$staticUrl%}/apps/island/images/help/h03.gif" width="240" height="170" /></div></td>
                <td>&nbsp;</td>
                <td><div align="center"><img src="{%$staticUrl%}/apps/island/images/help/h04.gif" width="240" height="170" /></div></td>
              </tr>
            </table>
          <table width="700" border="0" cellspacing="0">
              <tr>
                <td>【好友】</td>
            </tr>
              <tr>
                <td>好友之间可以通过偷钱拉客，来辅助增加的收入，攻击陷害和协同帮助，从互动中获得更大的游戏乐趣。</td>
              </tr>
          </table></td>
      </tr>
    </table>
  </div>
</div>

</body>
</html>
