<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>帮助 | 快乐岛主</title>
<link href="{%$staticUrl%}/apps/island/css_2011041102.css?v=1.01" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
.STYLE1 {
	color: #1363b7;
	font-size: 14px;
	align:left;
	font-style: normal;
	line-height: 30px;
	font-weight: bold;
}
.STYLE2 {
	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}

-->
.table-txt{ align:center; line-height:15px;}
.STYLE3 {
	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 18px;
	color: #333333;
	text-align: left;
}
.STYLE87 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
</style>
</head>

<body>
<div class="main">

{%include file="menu.phtml"%}

<div class="content" style="height:860px;padding-top:2px;">
  <div style="height:185px; background-image:url({%$staticUrl%}/apps/island/images/help/h-title.gif); background-repeat:no-repeat;">
    <table width="748" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td height="177" align="center" valign="bottom"><table width="740" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><div  class="STYLE87">
                <div align="right"><a href="{%$baseUrl%}/help/top">[基本介绍]&nbsp;</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help2">&nbsp;[操作说明]&nbsp;</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help5">&nbsp;[资费说明和支付方式]</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help6">&nbsp;[常见问答]</a></div>
            </div></td>
          </tr>
          <tr>
            <td><hr size="1" /></td>
          </tr>
          <tr>
            <td><div class="STYLE87">
                <div align="right"><a href="{%$baseUrl%}/help/help2">1.基本操作&nbsp;</a>&nbsp;<a href="{%$baseUrl%}/help/help3">2.游戏攻略</a></div>
            </div></td>
          </tr>
        </table></td>
      </tr>
    </table>
  </div>
  <div style="height:660px;">
    <table width="710" border="0" align="center" cellpadding="0" cellspacing="0" class="STYLE89">
      <tr>
        <td height="40"><p align="left" class="STYLE9"><img src="{%$staticUrl%}/apps/island/images/help/h08.gif" alt="基本介绍" /></p></td>
      </tr>
      <tr>
        <td height="22"><div align="left"><strong>2)游戏攻略</strong></div></td>
      </tr>
      <tr>
        <td><table width="710" border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td><strong>【设施建设】</strong></td>
            </tr>
            <tr>
              <td><p class="STYLE25">宝石建筑建议各位攒着宝石先建立高级的，也就是花费宝石多的。3级旋转木马、儿童乐园、鲸鱼管、海盗船、就先不要考虑的，分别需要花费38-23-17-17个宝石。其他的都在10以下。 <br />
                高级建筑给钱多，攒钱很重要。比如：后期一个旋转木马升级就要525000才能升到“旋转木马4Lv”，这么贵的建筑可以要花大钱的哦。 </p></td>
            </tr>
            <tr>
              <td><table width="650" border="0" align="center" cellpadding="0" cellspacing="0">
                <tr>
                  <td height="20"><hr size="1" /></td>
                </tr>
              </table></td>
            </tr>
          </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>【任务】 </strong></td>
              </tr>
              <tr>
                <td>每日任务为必做项，除了道具任务外一天需要使用十次道具可能相对于非RMB玩家有些难度，不过也是可以慢慢完成的。这些任务属于白拿的。 <br />
                  建设任务可以慢慢完成，不过建议在选择设施建造的时，最好跟着建设任务走，这样经验多，升级会相对轻松一些。 <br />
                  成就在任务里，也是任务的一种。不过可以获得称号，而称号可以带给你金钱和经验值。这个是可以慢慢获得的，不是非常困难。得到称号后每天有白拿的金钱和经验。虽然少点不过总比没有强。</td>
              </tr>
              <tr>
                <td><table width="650" border="0" align="center" cellpadding="0" cellspacing="0">
                  <tr>
                    <td height="20"><hr size="1" /></td>
                  </tr>
                </table></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>【港湾船位】 </strong></td>
              </tr>
              <tr>
                <td>船位建议14级以前可以保留4个到5个。有能力当然越多越好，14Lv是69个人满岛。建议船的到港时间可以用1小时的（16+3）的。 <br />
                  按照最低四个船位不被偷的话能有76个人。如果船位越多当然越好。 <br />
                  而船的到达时间可以和道具卡的加速卡联合使用，可以大大提高效率。原本要等20分钟才能到的，使用加速卡后缩短到10分钟，中间的时间可以装饰下岛屿，到别人的岛上溜达，帮自己拉点游客，弄点岛屿的金币等。</td>
              </tr>
              <tr>
                <td><table width="650" border="0" align="center" cellpadding="0" cellspacing="0">
                  <tr>
                    <td height="20"><hr size="1" /></td>
                  </tr>
                </table></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>【道具卡使用】</strong></td>
              </tr>
              <tr>
                <td>道具卡应用，10个道具卡可完成每日任务，大家可以看着使用点完成，不过建议抢夺卡谨慎使用别到时候来个RMB大战。呵呵。使用抢夺卡研究好后在使用，别使用半天得不了俩钱还得罪了别人以后遭到轰击。 <br />
                  目前只有防御卡和1级加速卡是可以金币购买的，防御卡建议保持使用。如果有条件保安卡也可以持续保持使用。保安卡防止拉客6小时。防御卡是防御不利道具卡8小时。 <br />
                  加速卡：加速卡可以大大提高赚钱的速度，使用方法是对将要到的船只加速，这样本来1小时只能接待3批游客（木筏系列），通过使用加速卡可以1小时接待6批了，可以多赚一倍的钱，具体为花20金买10分钟的加速卡，使用10张后还可完成日常任务得的奖励还有300金赚。</td>
              </tr>
              <tr>
                <td><table width="650" border="0" align="center" cellpadding="0" cellspacing="0">
                  <tr>
                    <td height="20"><hr size="1" /></td>
                  </tr>
                </table></td>
              </tr>
            </table>
          <table width="650" border="0" align="center" cellpadding="0" cellspacing="0">
            <tr>
              <td height="20"><div align="right"><a href="{%$baseUrl%}/help/help4">下一页</a></div></td>
            </tr>
          </table>
      </tr>
    </table>
  </div>
  

</div>

</body>
</html>
