<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>帮助 | 快乐岛主</title>
<link href="{%$staticUrl%}/apps/island/css_2011041102.css?v=1.01" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--

-->
.table-txt{ align:center; line-height:15px;}
.STYLE3 {
	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 18px;
	color: #333333;
	text-align: left;
}
.STYLE87 {	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
.STYLE1 {
	color: #1363b7;
	font-size: 14px;
	align:left;
	font-style: normal;
	line-height: 30px;
	font-weight: bold;
}
</style>
</head>

<body>
<div class="main">

{%include file="menu.phtml"%}

<div class="content" style="height:860px;padding-top:2px;">
  <div style="height:185px; background-image:url({%$staticUrl%}/apps/island/images/help/h-title.gif); background-repeat:no-repeat;">
    <table width="748" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td height="177" align="center" valign="bottom"><table width="740" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><div  class="STYLE87">
                <div align="right"><a href="{%$baseUrl%}/help/top">[基本介绍]&nbsp;</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help2">&nbsp;[操作说明]&nbsp;</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help5">&nbsp;[资费说明和支付方式]</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help6">&nbsp;[常见问答]</a></div>
            </div></td>
          </tr>
          <tr>
            <td><hr size="1" /></td>
          </tr>
          <tr>
            <td><div class="STYLE87">
                <div align="right"><a href="{%$baseUrl%}/help/help6">1.基本信息和操作</a>&nbsp;&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help9">2.互动操作</a></div>
            </div></td>
          </tr>
        </table></td>
      </tr>
    </table>
  </div>
  <div style="height:660px;">
    <table width="710" border="0" align="center" cellpadding="0" cellspacing="0" class="STYLE3">
      <tr>
        <td height="40"><img src="{%$staticUrl%}/apps/island/images/help/h10.gif" alt="基本操作" width="208" height="21" /></td>
      </tr>
      <tr>
        <td height="22" class="STYLE1"> <strong>1)基本信息和操作</strong></td>
      </tr>
      <tr>
        <td><table width="710" border="0" cellpadding="0" cellspacing="0">
          <tr>
            <td><strong>Q：如何使用道具卡？</strong></td>
          </tr>
          <tr>
            <td>A：点击游戏下部道具按钮，进入道具卡界面，如果您的仓库里没有卡片就需要到道具卡商店去购买。购买卡片后回到仓库，有一些卡片点击卡片可以直接使用，另外的卡片需要点击并指向目标才能使用。</td>
          </tr>
        </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td height="20"><hr size="1" /></td>
            </tr>
          </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td><strong>Q：岛屿如何变大？</strong></td>
            </tr>
            <tr>
              <td>A：当您的特定等级提升时，岛屿会随着等级扩展。如果想知道何时提升至下一级，只要查看游戏左上部的经验条就知道了。在弹出面板告诉您下一级会获得的奖品。升级后不仅能扩大岛屿，还可能会赠送道具卡、游客数量上限增加、解锁高级设施、解锁高级游船等等。</td>
            </tr>
          </table>
            <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：游客人数上限如何增长？</strong></td>
              </tr>
              <tr>
                <td>A：当您的岛屿等级提升时，游客上限就会随等级增加。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：日志是什么？</strong></td>
              </tr>
              <tr>
                <td>A：日志是记录您好友来访的行为以及您自己升级、完成任务等信息的地方。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：怎么完成任务？</strong></td>
              </tr>
              <tr>
                <td>A：点击游戏下部任务按钮，您会看到四类选择。所有任务就是所有类型的任务，日常任务是每天更新的任务信息，建设任务是根据您的等级才能开放的任务，成就任务是根据您的行为累计得到的奖励称号。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
          <table width="710" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><strong>Q：什么是称号？有什么用？</strong></td>
              </tr>
              <tr>
                <td>A：称号是完成成就任务后获得的，在您的头像上可以点击选择使用哪一个称号，不同称号会有不同的效果，有的可以每日增加经验值，有的可以每日获得金币，可以自己选择。称号的效果在第二天开始起作用。</td>
              </tr>
            </table>
          <table width="650" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="20"><hr size="1" /></td>
              </tr>
            </table>
         
          <table width="650" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>
                <td height="20"><div align="right"><a href="{%$baseUrl%}/help/help7">上一页</a></div></td>
              </tr>
            </table>
      </tr>
    </table>
  </div>
  

</div>

</body>
</html>
