<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>帮助 | 快乐岛主</title>
<link href="{%$staticUrl%}/apps/island/css_2011041102.css?v=1.01" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
.STYLE1 {
	color: #1363b7;
	font-size: 14px;
	align:left;
	font-style: normal;
	line-height: 30px;
	font-weight: bold;
}
.STYLE2 {
	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}

-->
.table-txt{ align:center; line-height:15px;}
.STYLE3 {
	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 18px;
	color: #333333;
	text-align: left;
}
.STYLE19 {	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 18px;
	color: #333333;
	text-align: left;
}
.STYLE20 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 18px;
	color: #333333;
	text-align: left;
}
.STYLE24 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
.STYLE25 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
.STYLE26 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
.STYLE27 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
.STYLE28 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
.STYLE29 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
.STYLE30 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
.STYLE31 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
.STYLE32 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
.STYLE33 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
.STYLE34 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
.STYLE35 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
.STYLE87 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
</style>
</head>

<body>
<div class="main">

{%include file="menu.phtml"%}

  <div class="content" style="height:860px;padding-top:2px;">
  <div style="height:185px; background-image:url({%$staticUrl%}/apps/island/images/help/h-title.gif); background-repeat:no-repeat;">
    <table width="748" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td height="177" align="center" valign="bottom"><table width="740" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><div  class="STYLE87">
                <div align="right"><a href="{%$baseUrl%}/help/top">[基本介绍]&nbsp;</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help2">&nbsp;[操作说明]&nbsp;</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help5">&nbsp;[资费说明和支付方式]</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{%$baseUrl%}/help/help6">&nbsp;[常见问答]</a></div>
            </div></td>
          </tr>
          <tr>
            <td><hr size="1" /></td>
          </tr>
          <tr>
            <td height="20"><div class="STYLE87">
                <div align="right"></div>
            </div></td>
          </tr>
        </table></td>
      </tr>
    </table>
  </div>
  <div style="height:660px;">
    <table width="740" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td align="center" valign="top"><table width="700" border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td height="40"><p align="left" class="STYLE9"><img src="{%$staticUrl%}/apps/island/images/help/h09.gif" alt="基本操作" width="230" height="21" /></p></td>
            </tr>
            <tr>
              <td height="22">&nbsp;</td>
            </tr>
            <tr>
              <td><table width="650" border="0" align="center" cellpadding="0" cellspacing="0">
                  <tr>
                    <td height="20"><div align="left">暂无内容</div></td>
                  </tr>
                </table>                <p class="STYLE10">&nbsp;</p></td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </div>
  

</div>

</body>
</html>
