<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>帮助 | 快乐岛主</title>
<link href="{%$staticUrl%}/apps/island/css_2011041102.css?v=1.01" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--

-->
.table-txt{ align:center; line-height:15px;}
.STYLE9 {color: #1363b7;
	font-size: 14px;
	align:left;
	font-style: normal;
	line-height: 30px;
	font-weight: bold;
}
.STYLE10 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
.STYLE11 {color: #1363b7;
	font-size: 14px;
	align:left;
	font-style: normal;
	line-height: 30px;
	font-weight: bold;
}
.STYLE12 {	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 18px;
	color: #333333;
	text-align: left;
}
.STYLE13 {
	color: #1363B7;
	font-weight: bold;
}
.STYLE3 {	font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 18px;
	color: #333333;
	text-align: left;
}
.STYLE87 {font-size: 12px;
	align:left;
	font-family: Arial, "宋体";
	line-height: 20px;
	color: #333333;
	text-align: left;
}
</style>
</head>

<body>
<div class="main">
{%include file="helpmenu.phtml"%}

  <div style="height:550px;">
    <table width="740" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td align="center"><table width="700" border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td height="40"><p align="left" class="STYLE9"><img src="{%$staticUrl%}/apps/island/images/help/h07.gif" alt="基本介绍" /></p></td>
            </tr>
            <tr>
              <td height="22" valign="bottom"><div align="center"><span class="STYLE11">欢迎来到快乐岛主</span></div></td>
            </tr>
            <tr>
              <td><p class="STYLE10"> “快乐岛主”是一款以海洋岛屿建设为题材的模拟经营类社区游戏。我们可以建设自己的小岛，布置和升级岛屿设施，通过增加船位，升级游船，从而带来更多游客，增加收入。我们可以去好友岛屿做出故障修理，拉走不耐烦的游客，拾取掉落的金币，送给好友礼物等增进友谊的互动行为。如果我们的等级够高，那么独特的装饰物、奇特的海岛造型，以及海洋和天空都将可以自由选择，让我们的岛屿成为与众不同的特殊小岛！</p></td>
            </tr>
          </table>
          <p><img src="{%$staticUrl%}/apps/island/images/help/help01.gif" width="717" height="225" border="0" usemap="#Map" /></p>
        </td>
      </tr>
    </table>
  </div>
  

</div>

<map name="Map" id="Map"><area shape="rect" coords="557,60,677,90" href="{%$baseUrl%}/help/help2" />
<area shape="rect" coords="527,97,643,125" href="{%$baseUrl%}/help/help3" />
<area shape="rect" coords="505,132,699,160" href="{%$baseUrl%}/help/help5" />
<area shape="rect" coords="477,168,601,195" href="{%$baseUrl%}/help/help6" />
</map></body>
</html>
