<link href="{%$staticUrl%}/apps/island/css.css?v=3.25" rel="stylesheet" type="text/css" />

<div class="main" style="height:560px;">
{%include file="menu.phtml"%}

    <div class="content">
    	<div class="yaoqing01">
            <table width="748" border="0" cellspacing="0" cellpadding="0">
            	<tr>
            		<td height="39" colspan="5" background="{%$staticUrl%}/apps/island/images/gift/songli-taobao01_01.gif">
            		<table width="100" border="0" align="right" cellpadding="0" cellspacing="0">
            			<tr>
            				<td><a href="/rrisland">返回游戏&gt;&gt;</a></td>
            			</tr>
            		</table>
            		</td>
            	</tr>
            	<tr>
            		<td height="355" width="43" background="{%$staticUrl%}/apps/island/images/gift/songli-taobao01_02.gif"></td>
            		<td height="355" width="191" background="{%$staticUrl%}/apps/island/images/gift/songli-taobao01_03.gif"></td>
            		<td height="355" width="315" background="{%$staticUrl%}/apps/island/images/gift/songli-taobao01_04.gif"></td>
            		<td height="355" width="157" background="{%$staticUrl%}/apps/island/images/gift/songli-taobao01_05.gif"></td>
            		<td height="355" width="42" background="{%$staticUrl%}/apps/island/images/gift/songli-taobao01_06.gif"></td>
            	</tr>
            	<tr>
            		<td height="34" background="{%$staticUrl%}/apps/island/images/gift/songli-taobao01_07.gif"></td>
            		<td bgcolor="#E5F6FD">&nbsp;</td>
            		<td bgcolor="#E5F6FD">
            		<table width="310" border="0" cellspacing="0" cellpadding="0">
            			<tr>
            				<td align="center"><a href="/rrisland/invite/friends"><img src="{%$staticUrl%}/apps/island/images/gift/songli-taobao01_08.gif" alt="邀请站内好友" width="129" height="33" border="0" /></a></td>
            			</tr>
            		</table>
            		</td>
            		<td bgcolor="#E5F6FD">&nbsp;</td>
            		<td height="34" background="{%$staticUrl%}/apps/island/images/gift/songli-taobao01_12.gif"></td>
            	</tr>
            	<tr>
            		<td height="37" colspan="5" background="{%$staticUrl%}/apps/island/images/gift/songli-taobao01_13.gif"></td>
            	</tr>
            </table>
    	</div>
   </div>
</div>


