<link href="{%$staticUrl%}/apps/island/css.css?v=3.25" rel="stylesheet" type="text/css" />

<div class="main">
{%include file="menu.phtml"%}

	<div class="chongzhicontent">
		<img src="{%$user.face%}" width="59" height="60" />
		<div class="xinxi">
			<div class="cname">{%$user.name|escape%}</div>
			<div class="shuzi">宝石： <span style="color:#3c7e9a;font-weight:bold;">{%$user.gold%}</span></div>
			<div class="fhyx"><a href="http://apps.{%$domain%}/rrisland"><img src="{%$staticUrl%}/apps/island/images/backg.gif" width="80" height="35" /></a></div>
		</div>
	</div>

	<div class="table">
		<ul>
		<li style="width:50px"></li>
		<li><a href="http://apps.{%$domain%}/rrisland/pay/top"><div class="nav_02">充值宝石</div></a></li>
		<li><a href="http://apps.{%$domain%}/rrisland/pay/orderlogs"><div class="nav_01">充值记录</div></a></li>
		<li><a href="http://apps.{%$domain%}/rrisland/pay/consumelogs"><div class="nav_02">消费记录</div></a></li>
		</ul>
	</div>

	<div class="content" style="padding-top:10px;padding-left:100px;width:650px;">
		<div class="chongzhi02"><span style="color:#0C67B6">充值记录</span> &nbsp;&nbsp;共{%$count%}条 </div>
		<table width="580" border="0" align="center" cellpadding="0" cellspacing="0" class="congzhitable">
		<tr>
			<td width="186"><strong>日期</strong></td>
			<td width="187"><strong>充值宝石数量</strong></td>
			<td width="97"><strong>消费</strong></td>
			<td width="110"><strong>充值方式</strong></td>
		</tr>
{%if $count>0 %}
{% foreach from=$logs item=log %}
		<tr class="table-line">
    		<td>{%$log.create_time|date_format:"%Y-%m-%d %H:%M:%S"%}</td>
    		<td><span class="pay-count">{%$log.gold%}</span></td>
    		<td>{%$log.amount%}人人豆</td>
    		<td>{%if $log.order_id==0%}系统赠送{%else%}人人支付平台{%/if%}</td>
  		</tr>
{%/foreach%}
{% /if %}
		</table>
	</div>
</div>

<iframe style="display: none;" src="{%$staticUrl%}/orderlogs.htm"></iframe>