<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>后台数据监测</title>
<link href="{%$staticUrl%}/renren/apps/island/compute/css.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div class="bigkuang">
<div class="bigtitle">后台数据监测</div>
<div class="select-kuang">
    <table width="750" border="0" cellpadding="0" cellspacing="0" class="table-title1">
    <tr>
      <td class="">2010年5月8日  星期六</td>
    </tr>
    </table>
    <table width="750" border="0" cellpadding="0" cellspacing="0" class="table-content1">
      <tr>
        <td width="90">平台</td>
        <td width="90"> 新增用户</td>
        <td width="90"> 活跃数       </td>
        <td width="90">活跃比</td>
        <td width="90"> 收入</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>人人           </td>
        <td>0000</td>
        <td>0000</td>
        <td>0000</td>
        <td>0000</td>
        <td><label>
          <a href="{%$baseUrl%}/compute/alluser/p/496700">进入</a>
        </label></td>
      </tr>
      <tr>
        <td>淘宝</td>
        <td>0000</td>
        <td>0000</td>
        <td>0000</td>
        <td>0000</td>
        <td><a href="{%$baseUrl%}/compute/alluser/p/496700">进入</a></td>
      </tr>
    </table>
</div>
</div>
</body>
</html>
