<?php

$aryInitSwf = array(
    'magicUi.swf',
    'decor1.swf?v=20111221v1',
    'desk1.swf',
    'door1.swf',
    'fire1.swf',
    'floor1.swf',
    'walldecor1.swf',
    'wall1.swf',
    'student1.swf',
    'music1.swf',
    'magicbook1.swf',
    'magicshow1.swf',
    'npc1.swf?v=20111221v1',
    'avatar1.swf',
    'monster1.swf',
    'bg1.swf?v=20111221v1',
    'item1.swf?v=20111221v1',
    'magicchange1.swf',
    'iconclass1.swf',
    'worldMapBg.swf',
	'MaxMpUi.swf',
    'bgicon1.swf',
    'levelplayerUp.swf',
    'TaskAwardUi.swf',
    'DailyRecordViewUI.swf',
    'ShopItemUi.swf',
    'studentFruitUi.swf',
    'StudentnamelistUi.swf',
    'TeachMagicClassUi.swf',
    'MixMagicViewUi.swf',

    'mine1.swf',
    'monster1.swf',
    'magichit1.swf',
    'magicmine1.swf',
    'mixitem.swf',
	'decorfb1.swf',
	'floorfb1.swf',
	'portalfb1.swf',
	'dungeon.swf',

    'HappyMagic.swf?v=20111221v1',
	'Rehandling.swf?v=20111221v1'
);

$aryInterface = array(
    'loadinit' => 'api/init',
    'loadstatic' => 'api/initbasic?v=1'.$apiBasicVer,
    'leaveedit' => 'api/diy',
    'transfer' => 'api/opendoor',
    'studymagic' => 'api/studentstudy',
    'interrupt' => 'api/studenthelp',
    'pickup' => 'api/pickup',
    'loadFriend' => 'api/friendlist',
    'buyItem' => 'api/buyitem',
    'friendsHome' => 'api/scene',
    'learnMagicClass' => 'api/studyteach',
    'learnTrans' => 'api/studytrans',
	'mix' => 'api/mix',
	'roomUp' => 'api/expandhouse',
	'useItem' => 'api/useitem',
	'useTrans' => 'api/trans',
	'studentAward' => 'api/studentaward',
	'enteredit' => 'api/loadbag',
	'unlockScene' => 'api/unlockscene',
    'moveScene' => 'api/changescene',
	'saveGuides' => 'api/tutorial',
	'finishTask' => 'api/finishtask',
	'killEnemy' => 'api/killmonster',
	'SignAwardInitStatic' => 'api/initdailyaward',
	'SignAward' => 'api/gaindailyaward',
	'FeedDataRequest' => 'api/activityaward',
	'RehandlingInit' => 'api/listcharacter',
	'RehandlingInitstatic' => 'api/initcharacter',
	'RehandlingRequest' => 'api/changecharacter',
	'SwitchScene' => 'api/entermap',
	'DungeonAct' => 'api/hitmonster',

	'GiftGetActInitStatic' => 'gift/list',
	'GiftGetActInit' => 'gift/user',
	'FriendRequest' => 'gift/friendrequest',
	'IgnoreGift' => 'gift/ignoregift',
	'ReceiveGift' => 'gift/receivegift',
	'SendGift' => 'gift/send',
	'ReleaseMyWish' => 'gift/mywish',
	'GiftGetKnowNew' => 'gift/hadread'

);

$aryModule = array(
    array(
            'name' => 'mainInfo',
            'className' => 'happymagic.display.view.MainInfoView',
            'algin' => 'top_center',
            'x' => 0,
            'y' => 0,
            'fx' => 0,
            'fy' => -200,
            'mvType' => 'fromTop',
            'mvTime' => 0.5,
			'layer' => 2
    ),
    array(
            'name' => 'sysMenu',
            'className' => 'happymagic.display.view.SysMenuView',
            'algin' => 'top_right',
            'x' => 10,
            'y' => 100,
            'fx' => -100,
            'fy' => 100,
            'mvType' => 'fromRight',
            'mvTime' => 0.5,
			'layer' => 2
    ),
    array(
            'name' => 'friends',
            'className' => 'happymagic.display.view.friends.FriendsView',
            'algin' => 'bottom_center',
            'x' => 0,
            'y' => 148,
            'fx' => 0,
            'fy' => 0,
            'mvType' => 'fromBottom',
            'mvTime' => 0.5,
			'layer' => 2
    ),
    array(
            'name' => 'menu',
            'className' => 'happymagic.display.view.MenuView',
            'algin' => 'bottom_center',
            'x' => 0,
            'y' => 182,
            'fx' => -740,
            'fy' => 0,
            'mvType' => 'fromLeft',
            'mvTime' => 0.5,
			'layer' => 2
    ),
    array(
        'name' => 'taskList',
        'className' => 'happymagic.display.view.task.TaskListView',
        'algin' => 'top_left',
        'x' => 15,
        'y' => 230,
        'fx' => -100,
        'fy' => 200,
        'mvType' => 'fromLeft',
        'mvTime' => 0.5,
		'layer' => 2
    ),
    array(
        'name' => 'actMenu',
        'className' => 'happyfish.manager.actModule.display.ActMenuView',
        'algin' => 'top_right',
        'x' => 50,
        'y' => 200,
        'fx' => 100,
        'fy' => 0,
        'mvType' => 'fromRight',
        'mvTime' => 0.5,
		'layer' => 2
    ),
    array(
        'name' => 'Rehandling',
        'className' => 'happymagic.display.view.rehandling.RehandlingView',
        'algin' => 'top_center',
        'x' => -327,
        'y' => 100,
        'fx' => 0,
        'fy' => 0,
        'mvType' => 'fromTop',
        'mvTime' => 0.5
    )
);

$swfConfig = array(
	'initSwf' 		    => $aryInitSwf,
	'mainClass' 		=> 'HappyMagicMain',
    'otherSwf'			=> array('guides.swf?v=20111223v1'),
	'interfaces'	    => $aryInterface,
	'bgMusic'		    => 'bgm01.mp3?v=20111221v1',
    'modules' 		    => $aryModule,
	'gameData'			=> array()
);